### ISSUE TITLE
Clicking to screen

### ISSUE THREAD

**Issue by shahmirzali49** [koukibadr/Cherry-Toast#18] opened 2021-12-13 11:56 UTC
When toast animation is on the screen, I also want to if the user wants to go to other pages, it goes. but it's not available if animation is on the screen. watch the video. at the end of animation I can navigate other screen

https://user-images.githubusercontent.com/49102327/145808026-75ce83ea-a274-4db2-bf58-59ba6ce565b5.mov

**Comment by koukibadr** [comment] 2021-12-13 19:53
@Shahmirzali-Huseynov  thanks for your feedback we will work on it it will be available in the next version

**Comment by Tristannos** [comment] 2022-05-31 07:18
> @Shahmirzali-Huseynov thanks for your feedback we will work on it it will be available in the next version

Still when the notification is called the rest of my screen is turning light black and does not respond to any action.
How can i fix this?

**Comment by shahmirzali49** [comment] 2022-08-02 20:09
@koukibadr any updates?

**Comment by koukibadr** [comment] 2022-08-06 07:35
Hello @Shahmirzali-Huseynov sorry for the late response I will publish a new version today contains the fix of the bug

**Comment by koukibadr** [comment] 2022-08-06 20:17
Hey @Shahmirzali-Huseynov , check this new version with the latest updates and the fix of this issue
[https://pub.dev/packages/cherry_toast](https://pub.dev/packages/cherry_toast)

**Comment by shahmirzali49** [comment] 2022-08-07 08:08
@koukibadr Actually I can't test whether it's fixed or not. cause I noticed in my last project removed this package. But in the future, I will use this package. thanks for the fixing. you can close the issue. when I use or test, I will comment.

**Comment by koukibadr** [comment] 2022-08-07 09:08
okay thanks for your support @Shahmirzali-Huseynov

**Comment by danielyuenhx** [comment] 2023-04-05 14:25
Hi @koukibadr, I am still having this issue with the overlay blocking user input when the toast is on the screen. I am using `cherry_toast: ^1.1.0`. How do I fix it?

**Comment by koukibadr** [comment] 2023-04-09 14:09
hello @danielyuenhx a new version is published please let me know if the problem persist

**Comment by danielyuenhx** [comment] 2023-04-17 11:31
Hi @koukibadr, the overlay still blocks components from being tapped until it times out. Furthermore, tapping on the overlay throws an error. I'm using `cherry_toast: ^1.2.0`

**Comment by koukibadr** [comment] 2023-04-17 12:50
@Shahmirzali-Huseynov I will verify this issue ASAP
Thanks for filling this issue

**Comment by baptistesx** [comment] 2023-05-25 14:13
Hey @koukibadr, i upgraded the package to v1.2.1 and I still have this issue :s

**Comment by koukibadr** [comment] 2023-05-27 08:54
Okay @baptistesx I will check this bug

**Comment by koukibadr** [comment] 2023-09-16 09:14
@baptistesx @Shahmirzali-Huseynov I just published a new version with @LeetaoGoooo PR fix (1.3.2)
@Shahmirzali-Huseynov if the issue is fixed you can close this issue

**Comment by koukibadr** [comment] 2023-09-25 21:59
Still not fixed version 1.3.3 (latest)

**Comment by LeetaoGoooo** [comment] 2023-09-26 01:38
I'm sorry I was unable to resolve the issue, but I noticed you seem to have already submitted a new PR,that's great~~

**Comment by koukibadr** [comment] 2023-09-26 08:08
@LeetaoGoooo your solution fix the issue of clicking on the screen but other issue is raised : toast position could not be changed [PR link](https://github.com/koukibadr/Cherry-Toast/pull/46) issue #45 so that's why I reverted your changes and changed the way we fix this issue I used `Overlay`

**Comment by LeetaoGoooo** [comment] 2023-09-26 14:11
> @LeetaoGoooo your solution fix the issue of clicking on the screen but other issue is raised : toast position could not be changed [PR link](https://github.com/koukibadr/Cherry-Toast/pull/46) issue #45 so that's why I reverted your changes and changed the way we fix this issue I used `Overlay`

Thank you very much for your patient explanation ♥️

**Comment by koukibadr** [comment] 2023-09-27 15:55
A new version has been published check it out it contains the fix to this issue 
if everything okay please close this issue (version 1.4.3)

**Closed as completed** 2023-10-01 14:51 UTC
Labels: bug, enhancement
